Algoritmo "Bom dia zap"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/09/2024
Var
// Seção de Declarações das variáveis
Nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Nome <- "Gustavo"
Escreva ("digite seu nome: ")
leia (Nome)
escreva ("tu é gay ", nome)
Fimalgoritmo